# This file was generated by GoReleaser. DO NOT EDIT.
class Rssfeeder < Formula
  desc ""
  homepage "https://github.com/mradile/rssfeeder"
  version "0.3.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mradile/rssfeeder/releases/download/0.3.7/rssfeeder_0.3.7_Darwin_x86_64.tar.gz"
    sha256 "7e5a10530778f8aa967430e261e0987df478269e6171533be0e5ecb708870a0b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mradile/rssfeeder/releases/download/0.3.7/rssfeeder_0.3.7_Linux_x86_64.tar.gz"
      sha256 "c017b67b2a181d96548a2d2c37571d6771c33954e7f20748cefe464aba6b6520"
    end
  end

  def install
    bin.install "rssfeederd"
    bin.install "rssfeeder"
  end
end
