# This file was generated by GoReleaser. DO NOT EDIT.
class Rssfeeder < Formula
  desc ""
  homepage "https://github.com/mradile/rssfeeder"
  version "0.3.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mradile/rssfeeder/releases/download/0.3.6/rssfeeder_0.3.6_Darwin_x86_64.tar.gz"
    sha256 "84130ff0f29a012e5ed6d1b7db10becaf581ea94422145d845d8358361bf54fc"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mradile/rssfeeder/releases/download/0.3.6/rssfeeder_0.3.6_Linux_x86_64.tar.gz"
      sha256 "28875dbdada95f0183d0ca56e15bf05da425e2f1e049e91ec09195b89141581a"
    end
  end

  def install
    bin.install "rssfeederd"
    bin.install "rssfeeder"
  end
end
