# This file was generated by GoReleaser. DO NOT EDIT.
class Rssfeeder < Formula
  desc ""
  homepage "https://github.com/mradile/rssfeeder"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mradile/rssfeeder/releases/download/0.4.0/rssfeeder_0.4.0_Darwin_x86_64.tar.gz"
    sha256 "9051a1e3e00368609281b05bdbce80a17bdfa6e743b212996fdf24762cf31ddd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mradile/rssfeeder/releases/download/0.4.0/rssfeeder_0.4.0_Linux_x86_64.tar.gz"
      sha256 "14a51b333fd17e86fd142e0cd43be321c0f57263ce1ee28c2a4437ca7c5764f9"
    end
  end

  def install
    bin.install "rssfeederd"
    bin.install "rssfeeder"
  end
end
